# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn build

      - run:
          name: zip artifacts
          command: zip -r ./dist_$CIRCLE_SHA1.zip ./dist
      - run:
          name: Install dependencies
          command: sudo apt-get -y -qq install awscli
      - run:
          name: uploading artifacts
          command: aws s3 cp ./dist_$CIRCLE_SHA1.zip s3://oberlo-artifacts/dist_$CIRCLE_SHA1.zip

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: bash .circleci/setup-heroku.sh
        - add_ssh_keys:
            fingerprints:
              - "08:28:bd:8f:c2:ee:74:9f:b8:c4:84:73:61:25:de:b8"
        - deploy:
            name: Deploy Master to Heroku
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git push heroku master
              fi



