# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: donatasp/oberlo-style-guide:0.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: yarn build

      - run:
          name: zip artifacts (only for master)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              zip -r ./dist_$CIRCLE_SHA1.zip ./dist
            fi

      - run:
          name: uploading artifacts (only for master)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 cp ./dist_$CIRCLE_SHA1.zip s3://oberlo-artifacts/dummy/dist_$CIRCLE_SHA1.zip
            fi

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "38:62:39:c4:f7:1a:12:f3:af:e3:55:88:bd:28:17:f2"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
            fi


